name: Kwiki-Indexer-Swish
version: 0.1.1
abstract: Kwiki Plugin index and search a Kwiki using swish-e
author: Russell Heilling <chewtoy@s8n.net
license: perl
distribution_type: module
requires:
  perl: 5.6.0
  Kwiki: 0.32
  Kwiki::Indexer: 0.1.0
  SWISH::API: 0.01
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
